application: datastore-key
version: 0-0-1
runtime: go
api_version: go1

handlers:
- url: /static/xml
  static_dir: static/default/xml
  mime_type: application/xml
- url: /static
  static_dir: static/default
  expiration: "1h"
- url: /.*
  script: _go_app